/*CREATE DATABASE if NOT EXISTS todo /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE todo;
DROP TABLE IF EXISTS task;*/
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE IF NOT EXISTS todo.public.task
(
    id          INTEGER      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description VARCHAR(100) NOT NULL,
    status      INTEGER NOT NULL,
    PRIMARY KEY (id)
);
INSERT INTO
    task
VALUES
    ( 1
    , 'aaa'
    , 1)
  , ( 2
    , 'bbb'
    , 2)
  , ( 3
    , 'ccc'
    , 0)
  , ( 4
    , 'ddd'
    , 1)
  , ( 5
    , 'eee'
    , 2)
  , ( 6
    , 'fff'
    , 0)
  , ( 7
    , 'ggg'
    , 1)
  , ( 8
    , 'hhh'
    , 2)
  , ( 9
    , 'jjj'
    , 0)
  , ( 10
    , 'kkk'
    , 1)
  , ( 11
    , 'lll'
    , 2)
  , ( 12
    , 'mmm'
    , 0)
  , ( 13
    , 'nnn'
    , 1)
  , ( 14
    , 'ooo'
    , 2)
  , ( 15
    , 'ppp'
    , 0);

